### ISSUE TITLE
Copy all related CameraModels.jl to this repo

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/CameraModels.jl#1]
https://github.com/yakir12/CameraModels.jl
https://github.com/JuliaRobotics/SensorFeatureTracking.jl
https://github.com/JuliaImages/CameraGeometry.jl

**Comment by dehann** [comment]
lets consolidate that here if there are no major objections.

**Comment by dehann** [comment]
Yakir mentioned that he is happy for us to consolidate code from his repo here.

**Comment by zsz00** [comment]
https://github.com/emmt/AndorCameras.jl

**Comment by zsz00** [comment]
what is implementation plan and schedule ?

**Comment by dehann** [comment]
Hi @zsz00 , thanks for all those links!  We started collecting the plan here, with 2 more tickets to go and then we can tag the first version:
https://github.com/orgs/JuliaRobotics/projects/9

I was able to close one ticket today.  Basically just beef up the testing a bit, consolidate the code a bit more and register v0.1.0.  If you perhaps have a unit test for pinhole cameras -- please consider sending a PR for that.

The links you added above seem to be to data capture from cameras.  This package is more meant for the actual intrinsic camera models, perhaps some of the extrinsics too.  A separate package would be needed to combine the CameraModels with data capture.  Maybe Video4Linux.jl etc.
